name: masoyinbo_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  iconsax: ^0.0.8

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    exclude:
      - assets/env/*
    outputs:
      class_name: AppAssets

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/jpegs/
    - assets/images/svgs/

  fonts:
  - family: Margarine
    fonts:
      - asset: assets/fonts/margarine/Margarine-Regular.ttf
  - family: Kanit
    fonts:
      - asset: assets/fonts/kanit/Kanit-Extralight.ttf
        weight: 200
      - asset: assets/fonts/kanit/Kanit-Light.ttf
        weight: 300
      - asset: assets/fonts/kanit/Kanit-Regular.ttf
        weight: 300
      - asset: assets/fonts/kanit/Kanit-Italic.ttf
        weight: 400
      - asset: assets/fonts/kanit/Kanit-Medium.ttf
        weight: 500
      - asset: assets/fonts/kanit/Kanit-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/kanit/Kanit-Bold.ttf
        weight: 700
      - asset: assets/fonts/kanit/Kanit-ExtraBold.ttf
        weight: 800
