name: masoyinbo_mobile
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.2
  cupertino_icons: ^1.0.8
  custom_timer: ^0.2.3
  envied: ^1.0.0
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_messaging: ^15.1.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^9.0.0
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.14.2
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.12
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  go_router: ^14.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  iconsax: ^0.0.8
  intl: ^0.19.0
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  percent_indicator: ^4.2.3
  pin_code_fields: ^8.0.1
  rxdart: ^0.28.0
  share_plus: ^10.0.2

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  envied_generator: ^1.0.0
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  integration_test:
    sdk: flutter
  intl_utils: ^2.8.7
  json_serializable: ^6.8.0


flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    exclude:
      - assets/env/*
    outputs:
      class_name: AppAssets

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/jpegs/
    - assets/images/svgs/

  fonts:
  - family: Margarine
    fonts:
      - asset: assets/fonts/margarine/Margarine-Regular.ttf
  - family: Kanit
    fonts:
      - asset: assets/fonts/kanit/Kanit-Extralight.ttf
        weight: 200
      - asset: assets/fonts/kanit/Kanit-Light.ttf
        weight: 300
      - asset: assets/fonts/kanit/Kanit-Regular.ttf
        weight: 300
      - asset: assets/fonts/kanit/Kanit-Italic.ttf
        weight: 400
      - asset: assets/fonts/kanit/Kanit-Medium.ttf
        weight: 500
      - asset: assets/fonts/kanit/Kanit-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/kanit/Kanit-Bold.ttf
        weight: 700
      - asset: assets/fonts/kanit/Kanit-ExtraBold.ttf
        weight: 800
